### ISSUE TITLE
Deprecate support for API 14 (Android 4.0)?

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#130]
Apologies if this has already been discussed, but I noticed in https://github.com/cyclestreets/android/blob/master/config.properties#L13 that the minSdkVersion is 14; according to the Android SDK manager, API version 14 is obsolete (10 and 15+ are OK though).

Should we change this or is there a good reason that we should still support API version 14?

**Comment by jezhiggins** [comment]
According to our usage statistics, around 5% of the current installs are on Android 4.0-4.04 which is API level 14-15.  This is below the "Travel and Local" apps category average, but still a reasonably large number of people.  While I'm happy to move the minSDK on, I'd want a good strong reason - an API we wanted to use that wasn't otherwise available, something like that.

As it is, we've only recently moved off 8, which will let us get away from the appcompat stuff and use native fragments and things.  (Haven't done that work yet, but we could!)

So,

**Comment by oliverlockwood** [comment]
@jezhiggins your comment appears truncated, but I'm taking the gist of this as "not yet" :smiley:

**Comment by oliverlockwood** [comment]
@jezhiggins any chance of you finishing your truncated comment above?  Would be useful to know what you were intending to write.

**Comment by jezhiggins** [comment]
I'm desperately trying to remember :)  

I think where I was going was I don't want to move just for the sake of moving.  However, if there's a good strong reason - an API that's not otherwise available, say - then let's look at it.

**Comment by oliverlockwood** [comment]
Cool, I'll close this issue for now.
