### ISSUE TITLE
Worldwide?

### ISSUE THREAD

**Issue by rugk** [cyclestreets/android#196]
> CycleStreets is a UK-wide cycle journey planner system

Why not make it worldwide? The OSM data is the same…

Also, on https://www.cyclestreets.net/, the map actually is populated worldwide.

**Comment by mvl22** [comment]
> Why not make it worldwide?

Because this requires very large amounts of RAM/CPU, which is expensive.

Donations of many thousands of pounds are very welcome :)
https://www.cyclestreets.net/donate/

Routing is actually now covers most of northern Europe, and many other cities around the world. A forthcoming API call will enable the area to be determined automatically.

**Comment by rugk** [comment]
> Routing is actually now covers most of northern Europe, and many other cities around the world

So if that is already the case, I think you need to change your text there…

> Because this requires very large amounts of RAM/CPU, which is expensive.

For routing, I assume. At least in case of the app, you could however do that on the client too… possibly. May need offline maps for this, but then you have a new feature: usable offline. Other map apps offer it too.

**Comment by mvl22** [comment]
> So if that is already the case, I think you need to change your text there

Funding is not assured, so we are wary to advertise it. Though main blocker is the lack of translation support in the app - code contributions welcome. We have a Transifex account set up, if the work to enable in the codebase can be done.

> you could however do that on the client too

Which is suddenly a totally different piece of code infrastructure. This would be nice in the long term but is way down the priority list. Lots of RAM would still be necessary...

Offline map mode is available with the map download. Code contributions would be welcome so we can move to a model of getting the offline data on-demand rather than up-front. Again, not a trivial change sadly.

**Comment by oliverlockwood** [comment]
I'm going to close this issue for now as it doesn't seem likely to be worked on in the near future.  Please feel free to comment / reopen if you disagree with this decision.
