### ISSUE TITLE
Blog formatting

### ISSUE THREAD

**Issue by si-the-pie** [cyclestreets/android#295]
As spotted by @DoccyB (CycleStreets's summer intern 2018) the title text overflows:

![screenshot_20180829-153406_cyclestreets](https://user-images.githubusercontent.com/361987/44795332-57bf3300-aba2-11e8-96d7-09444f11ebc8.jpg)

**Comment by mvl22** [comment]
Currently this is just a webpage loaded directly into the site. Can this be changed to a feed using the RSS output? I presume there will be some kind of Android RSS library.

https://www.cyclestreets.net/blog/feed/

**Comment by oliverlockwood** [comment]
I suspect this may be a fair bit of work, so I'm inclined to defer it till after the upcoming release, if that's OK.

**Comment by mvl22** [comment]
Yep, keen to get a stable 3.6 out rather than wait and stuff it with even more non-essential changes like this.

**Comment by oliverlockwood** [comment]
@mvl22 @si-the-pie FYI it looks like the latest version of the app (certainly on my Pixel 2) opens the blog in a browser window, outside of the app.  No changes were made by us to make this happen, so I suspect it's a change in Android itself.

To my mind this is fine, but you may think otherwise... :-/

**Comment by mvl22** [comment]
Ah, this is possibly because I've moved the blog over to our new organisation/corporate site:
https://www.cyclestreets.org/news/
with the feed therefore at
https://www.cyclestreets.org/news/feed/

Essentially we've moved the general non- journey planner -specific stuff out of .net.

There are a few references in that still to cyclestreets.net but I'll deal with those in due course.

**Comment by oliverlockwood** [comment]
We've had a negative review likely due to this change:
>Once you select the Blog option on the menu, there is no way to get back to the app. Everytime you open the app, it takes you directly to the webpage.

https://play.google.com/apps/publish?account=7698300952134656507#ReviewDetailsPlace:p=net.cyclestreets&reviewid=gp:AOqpTOGh_OGCAcu0vnbjNPvk-xrcyE3Gc7rnHQOxZNOQ54cVyjnKG-UAZtqZ5U1tdvm2cqY-OYbqqGWalhzqnw

Needs fixing.  I'll look at this as soon as I can.
