### ISSUE TITLE
Number the waypoints?

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#317]
On a Play Store review, a user has suggested "numbered waymarkers to avoid going the wrong way when routes cross."

Something to be looked into, and considered.

**Comment by jezhiggins** [comment]
Do the new vector images help here at all?

**Comment by oliverlockwood** [comment]
@jezhiggins bear in mind that as per my comments on https://github.com/cyclestreets/android/pull/365, we're not currently using the vectors directly.

But I'm sure that having them will help make this easier!

**Comment by HilaryN** [comment]
I'm keen to start on this so that I can then get started on #486 and #487.  With the darker evenings coming I'm often having to try and manually replan routes to avoid parks and deserted roads. I'm also doing quite a bit of cycle-buddying and trying to help my cycle buddies plan safer routes.

Where do I get the images from for the numbered waypoints?  @si-the-pie is this something you can magic up?  I'd have a go in Paint, but I've no idea about resolutions etc., particularly given the work @oliverlockwood  has done to precisely size and locate the images.

**Comment by HilaryN** [comment]
I'm just looking at drawing the number on top.  Though the waymarks seem a bit small at present to fit a number in, so I'd either have to make them bigger or float the number above the waymark.

**Comment by mvl22** [comment]
In the iOS app I'm pretty sure the numbers are added as text as there are only three icons:

https://github.com/cyclestreets/ios/tree/master/resources/images/x2/Wisps

**Comment by HilaryN** [comment]
Yes, will be much easier programmatically rather than having lots of images of numbered waymarks.

**Comment by HilaryN** [comment]
This shows the current-sized waymarks (first image) and the waymarks increased by a factor of 2.3, which I think is the minimum we need to increase them to in order to fit the number in so it is readable.  I think the black text is clearer.  The white doesn't look as clear as it does on the iPhone - maybe because the background is lighter here.

<img width="737" alt="Waymark examples 1 2_3" src="https://user-images.githubusercontent.com/59799824/130368187-89479d9d-dce6-44f5-a1d8-17c28da90025.PNG">

**Comment by oliverlockwood** [comment]
Hmm.  I'm not a big fan of making the markers so massive.  Are there any other options we can consider - e.g. putting the number above the marker, within an appropriate background colour shading to make it readable regardless of map context?

**Comment by oliverlockwood** [comment]
One thing we could also consider is to make visible numbering of the waypoints into an option which you can switch on or off?

**Comment by HilaryN** [comment]
Thanks for the feedback.

Yes, I could put the number above the marker and make it an option in the settings (probably switched off by default as most people probably wouldn't need it).  

I agree, the bigger the icons are, the more map it obscures.

**Comment by HilaryN** [comment]
Not having a background to the number means you can see more of the map.  On the other hand if you can't see the number (as in the "F" in the middle image), you can always zoom in/out to change what's behind it.

![image](https://user-images.githubusercontent.com/59799824/130517130-11e31867-757f-4939-9393-90c0384ad4ff.png)

**Comment by oliverlockwood** [comment]
I like this. Much cleaner. I'm happy if @mvl22 is.

**Comment by mvl22** [comment]
Definitely avoid having a setting. Settings for things that somehow don’t quite work is always a cop-out and is just bloat.

I do think the iPhone solution is right - the wisp size is appropriate and the numbers are within the wisp, which is visually strongest and avoids any confusion. Can the size be scaled to match?

![7E8A7934-055F-470C-B892-ADDD52E72C3F](https://user-images.githubusercontent.com/361423/130525744-f7941a1c-5662-4720-ae6f-68e37cec963c.png)

**Comment by HilaryN** [comment]
Just out of curiosity, what happens when you get to double figures, esp 20?  The markers don't seem wide enough on the iPhone.  Do they get wider to accommodate the bigger numbers?

**Comment by HilaryN** [comment]
Just out of curiosity, what happens when you get to double figures, esp 20?  The markers don't seem wide enough on the iPhone.  Do they get wider to accommodate the bigger numbers?
