### ISSUE TITLE
(Optionally) rotate the map with travel direction in LiveRide

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#391]
We occasionally get feedback about this, e.g. the following excerpt from a review:
>Would be better if the map rotated with travel direction

A brief search on the internet threw up this page: https://stackoverflow.com/questions/37575522/osmdroid-how-to-rotate-osm-map-as-per-devices-direction which suggests this isn't too infeasible to achieve; bearing in mind we're currently on the latest version of osmdroid it's probably worth having a go.

**Comment by jezhiggins** [comment]
OsmDroid does now support this natively - previously, IIRC, you had to do the maths (not a huge problem) and the translation (pita) yourself. Curiously the only OsmDroid sample that demonstrated the pinch-zoom issue, https://github.com/osmdroid/osmdroid/issues/1578, also does map rotation, so a quick squint at https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/location/SampleHeadingCompassUp.java should get us going.

**Comment by jezhiggins** [comment]
Call is mapView.setMapOrientation(degrees)

There's a tiny bit of adjustment to do to correct for the device portrait/landscape orientation. You can use the bearing from the location provider or from the compass.

**Comment by jezhiggins** [comment]
Oh - MapView now has setMapCenterOffset(x, y) which I think means we could move the marker down the screen, so as we rotated the you see more of the route in front of you.

**Comment by mvl22** [comment]
> OsmDroid does now support this natively

Awesome. This would be a great improvement to add.

**Comment by jezhiggins** [comment]
Very rough and ready first go, showing rotation with offset center. This has had no testing other than me walking up and down my garden, but I'll go for a walk round the block with it tomorrow to see how it holds up. 

![Screenshot_20200508-224644](https://user-images.githubusercontent.com/555337/81452456-df828080-917e-11ea-97bf-357ecf5863f4.jpg)

For reference - Anderton Park Road runs NE/SW. You can see that the wisp has also be rotated. We'd probably need to apply a reverse translation drawing those.

**Comment by mvl22** [comment]
Does the vector map also rotate, and fix the label alignment? Obviously a bitmap background can't do that, as shown.

**Comment by jezhiggins** [comment]
The rotation is done by the map view as it paints the screen, so is independent of the tile source. Consequently, the answers to your questions are yes, but no.

**Comment by jezhiggins** [comment]
It appears that mapsforge's own rotation implementation has its own problems - https://github.com/mapsforge/mapsforge/issues/7 - and it looks like they've kind of given up, which is a shame.

**Comment by jezhiggins** [comment]
Sorting out the wisp rotation turned out to be straightforward. The location icon handles it already. 

One thing that does need work is the icon. I wanted to use something that looked like a compass, but there isn't one in the icon set we're using and I couldn't be bothered to go hunting around for one at the time. (It was heading towards midnight and I'd got caught up "one more thinging" for nearly two hours.) 

Since then I've been thinking maybe the compass button should actually be a compass. When rotation (more correctly orientation) is off, it should just point up to the top of the screen. When orientation is on, perhaps we could try and make it dynamic so it shows where north is as you move. 

What you think?

**Comment by oliverlockwood** [comment]
I think yes to both. I see you've already pushed a commit to rotate the icon; I'll see if I can dig out a compass icon - the iconics library needs an upgrade anyway and perhaps there is now one available.

**Comment by jezhiggins** [comment]
Orienting the button turned out to be a one-liner :)

Use it for several short stretches this morning (unfortunately couldn't find my bar mount so could do an extended test) and it works really well. Orientation at lower speed or stopped, when using the compass, can be a bit jumpy but once you're on the move and we switch to gps it's really lovely.

**Comment by mvl22** [comment]
> Use it for several short stretches this morning (unfortunately couldn't find my bar mount so could do an extended test) and it works really well.

Great!

With the recent national announcement, the quicker we can get the app upgraded with things like this the better :) , there is definitely increased interest at the moment...

**Comment by oliverlockwood** [comment]
Here's my experience experimenting with the rotation implementation as it currently stands.  (I haven't yet taken it on a bike ride.)
-  I agree that in motion (even walking briskly up my short garden is enough) the direction is accurate and smooth.
-  When static, my experience outside my front door was that that it pointed the screen fairly reliably about ~30 degrees off to the left of where I was looking.  See the following photographs.  However Google Maps isn't perfect here so maybe my phone (a Pixel 2) just has a crap compass?

## 1. Looking ESE along the high street
<img src="https://user-images.githubusercontent.com/6017680/81506669-f8f70a00-92ef-11ea-8d87-6dd4e42ad7b1.jpeg" width="350">

## 2. Looking WNW along the high street
<img src="https://user-images.githubusercontent.com/6017680/81506674-feeceb00-92ef-11ea-8ac9-4fc801e6b7ea.jpeg" width="350">

## 3. Looking NNE across the road
<img src="https://user-images.githubusercontent.com/6017680/81506745-6f940780-92f0-11ea-83f7-650128692058.jpeg" width="350">

**Comment by oliverlockwood** [comment]
In addition, I agree strongly with Jez's point that:
> maybe the compass button should actually be a compass. 

**Perhaps @si-the-pie would like to provide some of his SVG skills here?**  I was thinking that perhaps we could derive something like the FontAwesome material design compass:
<a href="https://princenekretnine.com/css/fontawesome-free-5.0.6/advanced-options/raw-svg/regular/compass.svg"><img src="https://princenekretnine.com/css/fontawesome-free-5.0.6/advanced-options/raw-svg/regular/compass.svg" width="100"></a>
but with the following tweaks:
- having its initial alignment vertical (for simplicity of our code that will use and rotate it!) 
- having the "north" end tipped with red, for clarity

Of course an entirely custom compass icon would also be fine, I just thought I'd highlight a possibility to minimise the amount of work required.

**Comment by jezhiggins** [comment]
@oliverlockwood I think your experience with the compass might just be one of those things that depends on the device (and, theoretically at least, local magnetic field conditions). The fact that your compass is consistently off does suggest it is your phone rather than anything else, although I'm not sure any of them are especially accurate. The fact that the sample I worked from specifically called out using the gps bearing if you were moving would certainly support that.

**Comment by oliverlockwood** [comment]
Thanks @si-the-pie for submitting the compass icon SVG.  I've now raised #401 to make use of it.

**Comment by mvl22** [comment]
On my Android test device, using the 3.9 beta, I don’t see any rotation. I enter LiveRide but there is no rotation. Is there an extra button I have to push? Does it work when not using the vector maps?

**Comment by oliverlockwood** [comment]
@mvl22 you have to press the compass button.
