### ISSUE TITLE
LiveRide speech tweaks

### ISSUE THREAD

**Issue by jezhiggins** [cyclestreets/android#393]
Should announce metres and kilometres in full. Currently announces "Continue 100m" as "continue one hundred em" which is a bit rubbish.

If possible, I'd like to try and get road designations announced properly. "Wheeler's Lane A4040" is announced "Wheeler's Lane ay four thousand and forty" and "Castle Hill Road B1113" is announced "Castle Hill Road bee one thousand and thirteen." In an ideal world, we'd be able to transform those to "ay forty forty" and "bee treble one three", but even "ay four oh four oh" and "bee one one one three" would sound significantly more natural.

**Comment by oliverlockwood** [comment]
I have thought exactly the same thing.

**Comment by oliverlockwood** [comment]
I started looking at a regex to solve this but realised that our parlance is a little more complicated than that... so before I implement it, here's some proposed logic around this:

**1 or 2 digits** - leave & pronounce normally

**3 digits**
- if ends with 00, leave as-is, e.g. `A400` => pronounced as "Eh Four Hundred"
- else if ends with 0, split into single digit then double, e.g. `A230` => `A2 30` => pronounced as "Eh Two Thirty"
- otherwise, split into single digits, e.g. `B467` => `B4 6 7` => pronounced "Bee Four Six Seven"

**4 digits**
- if ends with 000, leave as-is, e.g. `A3000` => pronounced as "Eh Three Thousand"
- else if ends with 00, split off the "hundred", e.g. `B1200` => `B12 hundred` => pronounced as "Bee Twelve Hundred"
- else if either or both two digit separation ends with a zero, tokenise into two two-digits numbers,
   - e.g. `A1450` => `A14 50` => pronounced as "Eh Fourteen Fifty"
   - e.g. `B2031` => `B20 31` => pronounced as "Bee Twenty Thirty-One"
- else if any triple digits occur, sort those out, e.g. `B1113` => `B Triple 1 3`=> pronounced "Bee Triple One Three"
- otherwise, split into single digits, e.g. `A4123` => `A4 1 2 3` => pronounced as "Eh Four One Two Three"

@jezhiggins what do you think to that approach?

I should be able to keep this nicely isolated (and therefore unit-testable) by extending and extracting the `LiveRideState.speechify()` method.

**Comment by oliverlockwood** [comment]
PR now available for the metres / kilometres bit; I'll work on the road number implementation as an extension in due course.

**Comment by jf1** [comment]
That logic looks sound so :+1: for what would be a welcome enhancement.

Can you control the gaps, so it sounds like "B-20-20" rather than "B. 20. 20." or "B 20 20" ?

To clarify, I'm suggesting something like a 'half gap' within these single-word-roadnames rather than working around it by eg doubling up the following gap.

**Comment by oliverlockwood** [comment]
@jf1 thanks for the feedback.

I'll experiment with punctuation etc. but the last time I tried doing similar it wasn't very effective (the Android speech engine seems to just do what it wants, resisting outside control.)

**Comment by jezhiggins** [comment]
Yes, that logic seems excellent. Thank you :)

**Comment by oliverlockwood** [comment]
@jezhiggins I went out on a ride today and it told me about the A Four Three One and the B Treble Four Two.

It was glorious 😂
