### ISSUE TITLE
Enable voice navigation even when screen timed out

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#429]
User request:

"recently discovered your awesome android app! A small q - do you know how to make the voice navigation keep working even if the screen timesout? If I force the screen on it works - but then drains battery quite quickly."

https://twitter.com/sim0nw/status/1273872031864500229

**Comment by oliverlockwood** [comment]
I always switch off the screen, put it in my back pocket, and the voice commands continue. That is to say, this already works as far as I know.

If he/she wants one of us to take a closer look, then please ask them to provide us with full details of the version of the app, and the phone OS and hardware.

**Comment by mvl22** [comment]
Thanks! Have asked on that thread.

**Comment by HilaryN** [comment]
Voice instructions work for me, too, when screen is locked.

**Comment by oliverlockwood** [comment]
@mvl22 I'm closing this as this is generally known to work.  Feel free to re-open if more information is provided.

**Comment by mvl22** [comment]
https://twitter.com/simonwLDN/status/1305057040096731137

"you aware of any problems with android 11? Don't seem to be able to get live navigation to keep working in the background?"

Is this the same issue?

**Comment by swattor** [comment]
So... This was me (in both instances!). I did get it working but android 11 seemed to break it. I played around with various background settings, notification volumes, but could not get it to work. I know android 11 did make some changes to permissions so maybe this is now a valid issue on 11?

**Comment by jezhiggins** [comment]
What a pain in the bum.  Thanks for reporting it and we will try to investigate.

We might be able to isolate the problem on an emulator, but you may need to bear with a little while. As far as I know nobody in our little team is yet running Android 11 on a real phone, and some time real phones are what you need to shake out these permissions issues (assuming it is a permissions issue!)

**Comment by swattor** [comment]
Am happy to help debug if I can. I really like the app and would like to help contribute.

**Comment by oliverlockwood** [comment]
Thanks @swattor, much appreciated.

Are you signed up to the beta programme already or just on the regular releases?

(Hit Settings->About and the version is displayed at the bottom.  The latest regular release is 3.8.1/buildnum; the Beta track will show 3.9.0/buildnum.)

When we've had a chance to analyse and try out a fix / additional debugging, then this is the easiest way for you to receive it (admittedly along with everyone else on the beta track, but hey, it's beta).

**Comment by swattor** [comment]
I'm on the beta program (have been for a while)

**Comment by HilaryN** [comment]
I've downloaded an Android 11 emulator and done a quick test. Results so far:

![image](https://user-images.githubusercontent.com/59799824/93257147-59adbc00-f794-11ea-9905-073a666d2f5a.png)

**Comment by jezhiggins** [comment]
Thanks Hilary. That's helpful. Looks like it's something to do with what happen to the service when the app is in the background, doesn't it? On 15 Sep 2020 20:48, HilaryN <notifications@github.com> wrote:
I've downloaded an Android 11 emulator and done a quick test. Results so far:

**Comment by HilaryN** [comment]
Yes, I suspect so, as when I unlocked the screen after turning a corner with it locked, it did that thing of "Too far away" which it does if you skip a turn in the emulator - i.e. it was oblivious of the location changes while the screen was locked.
Different behaviour if I just went to the Home screen - the voice instructions continued, at least with TargetSdkVersion 29.

@swattor just to let you know, I think this is just an issue with Android 11 in the beta version for now - should be OK in the regular version.

**Comment by swattor** [comment]
Oh interesting! I'll test it out later. Got another ride to do tomorrow and will report back

**Comment by HilaryN** [comment]
To confirm: yes, we do need to request permission to access location in the background for Android 10 and higher.

https://developer.android.com/training/location/permissions

"On Android 10 (API level 29) and higher, you must declare the ACCESS_BACKGROUND_LOCATION permission in your app's manifest in order to request background location access at runtime. On earlier versions of Android, when your app receives foreground location access, it automatically receives background location access as well."

**Comment by oliverlockwood** [comment]
Good work @HilaryN, looking at those docs would have been my next step too.
Should be a fairly simple change to ask for the extra permissions when starting LiveRide, we already have a check for location permission at that point, so just an extension to what's asked for there.

**Comment by HilaryN** [comment]
Some screenshots...
This is what shows when first going in to LiveRide on Android 11:
![Screenshot_1600442331](https://user-images.githubusercontent.com/59799824/93618155-d0ce9480-f9ce-11ea-8cc8-41cf4f2c6e3c.png)
If one of the first 2 options is selected, you then tap the LiveRide button again and LiveRide starts.
I've then added the following (any feedback on wording of the last 3 paragraphs? ):
![Screenshot_1600444858](https://user-images.githubusercontent.com/59799824/93619635-bc8b9700-f9d0-11ea-9c57-19e8ba25656e.png)

When you click OK, one of the following system dialogues appear, depending on which option was selected in the first request:
![image](https://user-images.githubusercontent.com/59799824/93618810-ae894680-f9cf-11ea-8bbe-76abf92dfd60.png)

If you go to "Allow in Settings", you get the following system dialogue:
![Screenshot_1600443472](https://user-images.githubusercontent.com/59799824/93618995-f019f180-f9cf-11ea-9d4d-3268770a0f81.png)

**Comment by oliverlockwood** [comment]
@HilaryN that generally seems reasonable. I'd make some tweaks to the text, not least because of the stringent requirements of https://support.google.com/googleplay/android-developer/answer/9799150, including this statement:
> It MUST also include this language explaining background location usage to the user:
> 
> [This app] collects location data to enable ["feature"], ["feature"], ["feature"] even when the app is closed or not in use.

I think based on https://developer.android.com/training/location/permissions#request-background-location we'll probably need a slightly different set of text depending on the operating system version.  Here's my proposal:

## Common text
CycleStreets

CycleStreets collects location data to enable the LiveRide feature to provide turn-by-turn voice navigation directions, even when the app is closed or not in use.

The "closed or not in use" aspect allows the voice navigation to keep working if you lock the screen or switch to another app.

Background usage of location data will cease as soon as you leave the LiveRide part of the app.

## Android 10

Please select "Allow all the time" for LiveRide to be able to operate properly..

## Android 11 or higher

Please select "Allow in settings", then "Allow all the time" for LiveRide to be able to operate properly.

## Other things we need to cover here:
1.  These strings need to be translated (or at least translateable - please don't feel you have to seek out all the translations before raising the PR, I'd much rather progress the fix, and then we can retrofit the other languages)
2.  Based on the documentation on https://developer.android.com/training/location/permissions, please update the `cyclestreets-view` module `AndroidManifest.xml` to include `android:foregroundServiceType="location"` in the declaration of the `LiveRideService`.

**Comment by jezhiggins** [comment]
While the overwhelming majority will be fine, I'm absolutely certain we'll get queries about the word "collect". 

Google's requires seem to assume implicitly that the location data is sent to the backend. Of course, we don't do this, so I wonder if we can include a line to that effect.

**Comment by oliverlockwood** [comment]
Good point Jez. Feel free to edit my comment to address this or I'll take a look again tonight.

Unfortunately we apparently have to use that literal language.

**Comment by HilaryN** [comment]
Given we have to use the phrase "CycleStreets collects location data to enable..." we could add something like: "The app" (or "CycleStreets") "doesn't store or send your location data anywhere.  It only uses your location to determine the next turn instruction and calculate your remaining journey."

Should we also add something like: 
'If you don't need to use voice navigation when the screen is locked or when you are using another app, then there is no need for you to select "Allow all the time".  Selecting "Allow only when using the app" or "Ask every time" is sufficient to use LiveRide with the screen switched on and LiveRide displaying in the foreground.'

**Comment by mvl22** [comment]
I was going to raise the same issue about the term 'collect'. We aren't trying to be like Google and hoover up location data. We aren't tracking users ("collecting" location data) in that way.

The only circumstance when the location is sent to the server is if a replan from the current live GPS location is sent, from that point to the final destination. However, we have no way of actually knowing if this is a replanned journey or a fresh journey, and indeed no way to know if this is actually a satnav journey from a current location or just an arbitary prospective journey.

**Comment by mvl22** [comment]
We need to get this live soon - this e-mail arrived today:

> To help prevent unnecessary access to background location, the policy will allow access only if it’s critical to the app’s core functionality and provides clear user benefit. We found that many apps that requested background location don’t actually need it. Removing or changing it to foreground can help apps be battery-efficient and avoid poor app ratings when users don’t want to share their location.
> 
> Issue with your apps:
> 
> We found that at least one of your apps may be requesting background location data. If your app uses background location data, you must remove access to location in the background or get approval for the requests by March 29, 2021 so your app can stay on Google Play.
> 
> Action may be required: Submit your apps for review and approval by March 29, 2021.

**Comment by swattor** [comment]
I might have a crack at trying to fix this - unless you already have plans to.

**Comment by HilaryN** [comment]
@swattor is this still not working in beta version on Android 11?

**Comment by swattor** [comment]
I haven't tried it I'm afraid - I just assumed nothing had been done from the previous comment :-). Was looking for ways to contribute to the project.

**Comment by HilaryN** [comment]
I'm getting confused myself as I think this issue led to others, including the one just mentioned by mvl here.  However, I'm pretty sure the original issue reported by you here is fixed in beta, so it would be good if you could double-check on your phone.
I think @oliverlockwood  is ironing out any other related issues which cropped up.
Plenty of other issues to work on though if any take your fancy :-)

**Comment by oliverlockwood** [comment]
@mvl22 for future reference, it's not particularly helpful to reopen a fixed issue to say "get the beta version live".  If you want to, then raise a new issue and link any relevant closed ones.

I'm now working on getting the beta version live but this ticket should not be open for that.

**Comment by mvl22** [comment]
Sorry, yes, not sure why I posted that on this issue! Apologies.
