### ISSUE TITLE
App crash accessing settings since update to Android 10

### ISSUE THREAD

**Issue by smsm1** [cyclestreets/android#436]
Yesterday my Fairphone 3 was updated to Android 10. Since then opening the left sidebar and tapping settings causes the app to crash.

Prior to the OS update this wasn't an issue.

Version 3.9.0 on the Google play app store. I have beta updates enabled.

I've tried clearing the cache and app data, both of which have the same crash.

**Comment by jezhiggins** [comment]
Hi Shaun,

Found this crash in the logs - it's related the vector maps, although can't immediately see why it would be failing. That's an area I'm working on at the moment, so I'll try and patch this up as quickly as I can as it's all in the process of being rewritten anyway.

**Comment by jezhiggins** [comment]
java.lang.NullPointerException: 
  at net.cyclestreets.util.MapPack.availableMapPacks (MapPack.java:38)
  at net.cyclestreets.SettingsFragment.populateMapFileList (SettingsFragment.kt:137)
  at net.cyclestreets.SettingsFragment.setupMapFileList (SettingsFragment.kt:132)
  at net.cyclestreets.SettingsFragment.onCreate (SettingsFragment.kt:53)

**Comment by HilaryN** [comment]
My Fairphone 3 updated this morning to Android 10 - having same issue, beta version (and same in Pixel 3 XL API 29 emulator).

Good to see it's being sorted :-)

**Comment by oliverlockwood** [comment]
FWIW the line in question in the `MapPack` class is:
```java
    for (final File mapDir : obbDir.listFiles(new CycleStreetsMapFilter())) {
```

We already know `obbDir` is non-null by this point; the problem is that `listFiles()` may return `null`, according to the Javadoc  for this method.

I'm not sure why upgrading to Android 10 will have caused this issue to arise, but looking at https://stackoverflow.com/questions/60147351/cannot-reach-obb-expansion-file-on-android-10-device-if-apk-and-obb-is-downloade it seems like Android is at least discouraging apps from sharing OBBs with each other.  Anyway, like Jez says, this problem will be irrelevant once we've switched to his new mechanism.
